# Use a slim Node.js base image
FROM node:20-slim AS build

# Set environment variable for pnpm home directory
ENV PNPM_HOME="/pnpm"

# Add pnpm to PATH (optional, consider using `pnpm config set add-path` as discussed earlier)
RUN corepack enable

# Copy project files to the container
WORKDIR /backdev
COPY package*.json ./
COPY prisma ./prisma/

# Install dependencies and pass-in
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
COPY . .

# Build the application in one stage
RUN pnpm build

# Final stage with a smaller image size
FROM build AS final
COPY --from=build /backdev/dist /backdev/dist
EXPOSE 3000
CMD [ "pnpm", "start:prod" ]
