# First stage: base image with Node.js 20
FROM node:20 AS base

# Install pnpm globally
RUN npm i -g pnpm

# Second stage: dependencies stage
FROM base AS dependencies 
WORKDIR /usr/src/app
COPY package.json pnpm-lock.yaml ./
COPY src/Infrastructure/prisma ./
RUN pnpm install

# Third stage: build stage
FROM base AS build
WORKDIR /usr/src/app
COPY . .
COPY --from=dependencies /usr/src/app/node_modules ./node_modules

# Build the application and Prune dev dependencies
RUN pnpm build
RUN pnpm prune --prod

# Fourth stage: deployment stage with a smaller Alpine image
FROM node:20-alpine3.19 AS deploy
WORKDIR /usr/src/app
RUN npm i -g pnpm prisma
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/package.json ./package.json
COPY --from=build /usr/src/app/src/Infrastructure/prisma/* ./prisma

# Generate Prisma client
RUN pnpm prisma generate

# Expose port and start app
EXPOSE 3000
CMD [ "pnpm", "start:prod" ]